# =========================
# Site basics
# =========================
locale          : "en-US"
site_theme      : "default"   # "default" | "air"
title           : "Xin Zheng — Academic Homepage"
title_separator : "-"
name            : &name "Xin Zheng"
description     : &description "Academic portfolio of Xin Zheng (Economics & Computation, Duke University)"
url             : "https://xin-lyra-zheng.github.io"   # 先用 GitHub Pages 域名；若以后绑定自定义域名，改为 https://<your-domain>
baseurl         : ""                                   # 用户主页必须为空
repository      : "xin-lyra-zheng/xin-lyra-zheng.github.io"

# =========================
# Author (left sidebar)
# =========================
author:
  # Bio
  avatar     : "/images/xin-profile.png"        # 放在 /images/ 或根目录，保持路径一致
  name       : "Xin Zheng"
  pronouns   :                      # 留空，若需要再填，例如 "she/her" 或 "he/him"
  bio        : "M.S. in Economics & Computation @ Duke University. Research: Interpretable ML, Hypergraph Learning, Decision Trees + GAMs, AI alignment/fairness."
  location   : "Durham, NC"
  employer   : "Duke University"
  uri        :
  email      : "xin.zheng@duke.edu"

  # Academic IDs (留空表示不显示)
  academia      :
  arxiv         :
  googlescholar :https://scholar.google.com/citations?hl=zh-CN&user=FQUBnVQovvwC                   # 建议填你的 Scholar 主页 URL
  inspire-hep   :
  impactstory   :
  orcid         :
  semantic      :
  pubmed        :
  researchgate  :
  scopus        :

  # Dev profiles
  github        : "xin-lyra-zheng"
  bitbucket     :
  codepen       :
  dribbble      :
  kaggle        :
  stackoverflow :

  # Social
  artstation :
  bluesky    :                        # 例如 "xinzheng.bsky.social"
  facebook   :
  flickr     :
  foursquare :
  goodreads  :
  google_plus:
  keybase    :
  instagram  :
  lastfm     :
  linkedin   :                        # 例如 "xin-zheng-<id>"
  mastodon   :
  medium     :
  pinterest  :
  soundcloud :
  steam      :
  telegram   :
  tumblr     :
  twitter    :                        # X/Twitter 用户名
  vine       :
  weibo      :
  wikipedia  :
  xing       :
  youtube    :
  bilibili     : https://space.bilibili.com/174805325?spm_id_from=333.1007.0.0

# =========================
# Publication Categories
# =========================
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# =========================
# Site settings
# =========================
teaser            :
breadcrumbs       : false
words_per_minute  : 160
future            : true
read_more         : "disabled"
talkmap_link      : false

comments:
  provider        :
  disqus:
    shortname     :
  discourse:
    server        :
  facebook:
    appid         :
    num_posts     :
    colorscheme   :

staticman:
  allowedFields   : ['name', 'email', 'url', 'message']
  branch          : "gh-pages"
  commitMessage   : "New comment."
  filename        : comment-{@timestamp}
  format          : "yml"
  moderation      : true
  path            : "_data/comments/{options.slug}"
  requiredFields  : ['name', 'email', 'message']
  transforms:
    email         : "md5"
  generatedFields:
    date:
      type        : "date"
      options:
        format    : "iso8601"

atom_feed:
  hide            : false
  path            :

# =========================
# SEO & sharing
# =========================
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username        :
facebook:
  username        :
  app_id          :
  publisher       :
og_image          :
og_description    :
social:
  type            : Person
  name            : "Xin Zheng"
  links           : []   # 可以填社交链接数组

# =========================
# Analytics
# =========================
analytics:
  provider        : "false"
  google:
    tracking_id   :

# =========================
# Build includes/excludes
# =========================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# =========================
# Markdown/convert
# =========================
markdown           : kramdown
highlighter        : rouge
lsi                : false
excerpt_separator  : "\n\n"
incremental        : false
kramdown:
  input            : GFM
  hard_wrap        : false
  auto_ids         : true
  footnote_nr      : 1
  entity_output    : as_char
  toc_levels       : 1..6
  smart_quotes     : lsquo,rsquo,ldquo,rdquo
  enable_coderay   : false

# =========================
# Collections
# =========================
collections:
  teaching:
    output    : true
    permalink : /:collection/:path/
  publications:
    output    : true
    permalink : /:collection/:path/
  portfolio:
    output    : true
    permalink : /:collection/:path/
  talks:
    output    : true
    permalink : /:collection/:path/

# =========================
# Defaults
# =========================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout         : single
      author_profile : true
      read_time      : true
      comments       : true
      share          : true
      related        : true
  - scope:
      path: ""
      type: pages
    values:
      layout         : single
      author_profile : true
  - scope:
      path: ""
      type: teaching
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true
  - scope:
      path: ""
      type: publications
    values:
      layout         : single
      author_profile : true
      share          : true
      comments       : true
  - scope:
      path: ""
      type: portfolio
    values:
      layout         : single
      author_profile : true
      share          : true
      comment        : true
  - scope:
      path: ""
      type: talks
    values:
      layout         : talk
      author_profile : true
      share          : true

# =========================
# Sass / Output / Plugins
# =========================
sass:
  sass_dir : _sass
  style    : compressed

permalink : /:categories/:title/
timezone  : America/New_York

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =========================
# Archives & HTML compression
# =========================
category_archive:
  type : liquid
  path : /categories/
tag_archive:
  type : liquid
  path : /tags/

compress_html:
  clippings : all
  ignore:
    envs    : development
